import { all_routes } from "../../../feature-module/routes/all_routes";

const routes = all_routes;

export const SidebarData = [
  {
    tittle: "Main Menu",
    roles: ["admin", "doctor", "patient"] as const,
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Dashboard",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "layout-dashboard",
        base: "dashboard",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Admin Dashboard", link: routes.dashboard },
        ],
      },
    ],
  },
  {
    tittle: "Doctor",
    roles: ["doctor"] as const,
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Appointments",
        link: routes.doctorsappointments,
        submenu: false,
        showSubRoute: false,
        icon: "calendar-check",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Messages",
        link: routes.doctorMessages,
        submenu: false,
        showSubRoute: false,
        icon: "messages",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Prescriptions",
        link: routes.doctorsprescriptions,
        submenu: false,
        showSubRoute: false,
        icon: "prescription",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  {
    tittle: "Patient",
    roles: ["patient"] as const,
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Appointments",
        link: routes.patientappointments,
        submenu: false,
        showSubRoute: false,
        icon: "calendar-check",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Messages",
        link: routes.patientMessages,
        submenu: false,
        showSubRoute: false,
        icon: "messages",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Prescriptions",
        link: routes.patientPrescriptions,
        submenu: false,
        showSubRoute: false,
        icon: "prescription",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  {
    tittle: "Clinic",
    roles: ["admin"] as const,
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Doctors",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "user-plus",
        base: "Doctors",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Doctors", link: routes.doctors },
          { label: "Doctor Details", link: routes.doctorsList },
          { label: "Add Doctor", link: routes.addDoctors },
          { label: "Doctor Schedule", link: routes.doctorScheduleClini },
        ],
      },
      {
        label: "Patients",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "user-heart",
        base: "Patients",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Patients", link: routes.patients },
          { label: "Patient Details", link: routes.patients },
          { label: "Create Patient", link: routes.createPatient },
        ],
      },
      {
        label: "Appointments",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "calendar-check",
        base: "Patients",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Appointments", link: routes.appointments },
          { label: "New Appointment", link: routes.newAppointment },
          { label: "Calendar", link: routes.appointmentCalendar },
        ],
      },
      {
        label: "Locations",
        link: routes.locations,
        submenu: false,
        showSubRoute: false,
        icon: "map-pin",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Services",
        link: routes.services,
        submenu: false,
        showSubRoute: false,
        icon: "map-pin",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "specializations",
        link: routes.specializations,
        submenu: false,
        showSubRoute: false,
        icon: "user-shield",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },

      {
        label: "Assets",
        link: routes.assets,
        submenu: false,
        showSubRoute: false,
        icon: "asset",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Activities",
        link: routes.activities,
        submenu: false,
        showSubRoute: false,
        icon: "activity",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Messages",
        link: routes.messages,
        submenu: false,
        showSubRoute: false,
        icon: "messages",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "File Manager",
        link: routes.fileManager,
        submenu: false,
        showSubRoute: false,
        icon: "folder",
        base: "application",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  {
    tittle: "HRM",
    roles: ["admin"] as const,
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Staffs",
        link: routes.staffs,
        submenu: false,
        showSubRoute: false,
        icon: "users-group",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Departments",
        link: routes.hrmDepartments,
        submenu: false,
        showSubRoute: false,
        icon: "building-bank",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Designation",
        link: routes.designation,
        submenu: false,
        showSubRoute: false,
        icon: "user-cog",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },

      {
        label: "Attendance",
        link: routes.attendance,
        submenu: false,
        showSubRoute: false,
        icon: "user-check",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Activities",
        link: routes.activities,
        submenu: false,
        showSubRoute: false,
        icon: "activity",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Leaves",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "users-minus",
        base: "Patients",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Leaves", link: routes.leaves },
          { label: "Leave Type", link: routes.leaveType },
        ],
      },
      {
        label: "Holidays",
        link: routes.holidays,
        submenu: false,
        showSubRoute: false,
        icon: "home-exclamation",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Payroll",
        link: routes.payroll,
        submenu: false,
        showSubRoute: false,
        icon: "coin",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  {
    tittle: "Finance & Accounts",
    roles: ["admin"] as const,
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Expenses",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "credit-card",
        base: "Patients",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Expenses", link: routes.expenses },
          { label: "Expense Category", link: routes.expenseCategory },
        ],
      },
      {
        label: "Income",
        link: routes.income,
        submenu: false,
        showSubRoute: false,
        icon: "coins",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Invoices",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "file-invoice",
        base: "Patients",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Invoices", link: routes.invoices },
          { label: "Invoice Details", link: routes.invoices },
        ],
      },
      {
        label: "Payments",
        link: routes.payments,
        submenu: false,
        showSubRoute: false,
        icon: "cards",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Transactions",
        link: routes.transactions,
        submenu: false,
        showSubRoute: false,
        icon: "transition-right",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  {
    tittle: "Administration",
    roles: ["admin"] as const,
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Reports",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "report",
        base: "Users",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Income Report", link: routes.incomeReport },
          { label: "Expense Report", link: routes.expenseReport },
          { label: "Profit & Loss", link: routes.profitloss },
          { label: "Appointment Report", link: routes.appointmentReport },
          { label: "Patient Report", link: routes.patientReport },
        ],
      },
    ],
  },
  {
    tittle: "Settings",
    roles: ["admin"] as const,
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Account Settings",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "user-cog",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Profile",
            link: routes.profilesettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Security",
            link: routes.securitysettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Notifications",
            link: routes.notificationssettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Website Settings",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "world-cog",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Organization",
            link: routes.organizationsettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Prefixes",
            link: routes.prefixessettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Maintenance Mode",
            link: routes.maintenancemodesettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Preferences",
            link: routes.preferencessettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Clinic Settings",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "building-hospital",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Appointment",
            link: routes.appointmentsettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Working Hours",
            link: routes.workinghourssettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Cancellation Reason",
            link: routes.cancellationreasonsettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "App Settings",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "device-mobile-cog",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Invoice Settings",
            link: routes.invoicesettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "System Settings",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "device-desktop-cog",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "GDPR Cookies",
            link: routes.gdprcookiessettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Finance & Accounts",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "settings-dollar",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Payment Methods",
            link: routes.paymentmethodssettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Bank Accounts",
            link: routes.bankaccountssettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Tax Rates",
            link: routes.taxratessettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Currencies",
            link: routes.currenciessettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
    ],
  },
];
